[tool.poetry]
name = "stockchartsalerts"
version = "0.0.1"
description = "Bot for alerts from stockcharts.com"
authors = ["Major Hayden <fmajor@mhtx.net>"]
repository = "https://github.com/major/stockchartsalerts"
documentation = "https://major.github.io/stockchartsalerts/"
readme = "README.md"
packages = [
  {include = "stockchartsalerts"}
]

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
discord-webhook = "^1.3.1"
schedule = "^1.2.2"
python-dateutil = "^2.9.0-post.0"
pytz = "^2024.1"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
pytest-cov = "^5.0.0"
deptry = "^0.18.0"
mypy = "^1.11.1"
pre-commit = "^3.8.0"
tox = "^4.16.0"
freezegun = "^1.5.1"
pytest-sugar = "^1.0.0"
pytest-randomly = "^3.15.0"
pytest-httpx = "^0.30.0"
types-python-dateutil = "^2.9.0.20240316"
types-pytz = "^2024.1.0.20240417"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = ["stockchartsalerts"]
disallow_untyped_defs = "True"
disallow_any_unimported = "True"
no_implicit_optional = "True"
check_untyped_defs = "True"
warn_return_any = "True"
warn_unused_ignores = "True"
show_error_codes = "True"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--cov=stocknews", "--cov-report=term-missing", "--cov-report=html"]

[tool.ruff]
target-version = "py39"
line-length = 120
fix = true
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
]

[tool.ruff.format]
preview = true

[tool.coverage.report]
skip_empty = true

[tool.coverage.run]
branch = true
source = ["stockchartsalerts"]


[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
